#!/usr/bin/env python3
"""
Train an autoencoder for ESP32 sensor anomaly detection.

Generates src/model_autoencoder.h with weights, biases,
normalization params, and threshold.

Usage:
    pip install -r server/train/requirements.txt
    python3 server/train/train_autoencoder.py
"""

import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
import os

np.random.seed(42)
tf.random.set_seed(42)

OUTPUT_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "src", "model_autoencoder.h"
)

# ─── 1. Генерация синтетических данных ───────────────────────


def generate_farm_data(n_samples=5000):
    """Генерирует нормальные показания фермы."""
    temp = np.random.normal(24, 3, n_samples)
    hum = np.random.normal(45, 8, n_samples)
    hum = np.clip(hum + -2 * (temp - 24), 20, 85)

    soil  = np.random.uniform(800, 3500, n_samples)
    water = np.random.uniform(500, 3800, n_samples)
    light = np.random.uniform(500, 4000, n_samples)
    steam = np.random.uniform(200, 1800, n_samples)

    return np.column_stack([temp, hum, soil, water, light, steam])


def add_anomalies(data, fraction=0.02):
    """Добавляет выбросы для тестирования."""
    n = len(data)
    n_anom = int(n * fraction)
    idx = np.random.choice(n, n_anom, replace=False)
    anom = data.copy()
    for i in idx:
        feat = np.random.randint(0, 6)
        if feat < 2:
            anom[i, feat] = np.random.choice([-15, 60])   # выброс температуры
        else:
            anom[i, feat] = np.random.choice([-500, 4500])  # выброс ADC
    return anom

# ─── 2. Подготовка данных ────────────────────────────────────

print("Генерация данных...")
X_clean = generate_farm_data(5000)
X_test  = add_anomalies(generate_farm_data(2000))

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X_clean)
X_test_norm = scaler.transform(X_test)

# ─── 3. Построение автоэнкодера ──────────────────────────────

print("Построение модели...")
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, "relu", input_shape=(6,)),
    tf.keras.layers.Dense(2, "relu"),
    tf.keras.layers.Dense(4, "relu"),
    tf.keras.layers.Dense(6, "linear"),
])

model.compile(optimizer="adam", loss="mse")
model.summary()

# ─── 4. Обучение ─────────────────────────────────────────────

print("Обучение...")
history = model.fit(
    X_norm, X_norm,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1,
)

# ─── 5. Расчёт порога аномалии ───────────────────────────────

recon = model.predict(X_norm, verbose=0)
mse_per_sample = np.mean((X_norm - recon) ** 2, axis=1)
threshold = float(np.percentile(mse_per_sample, 95))
final_loss = float(history.history["loss"][-1])

print(f"\nИтоговая потеря (MSE): {final_loss:.6f}")
print(f"Порог аномалии (95-й перцентиль): {threshold:.6f}")

# ─── 6. Тестирование на аномалиях ────────────────────────────

recon_test = model.predict(X_test_norm, verbose=0)
mse_test = np.mean((X_test_norm - recon_test) ** 2, axis=1)
anomaly_rate = np.mean(mse_test > threshold)
print(f"Доля обнаруженных аномалий: {anomaly_rate * 100:.1f}%")

# ─── 7. Извлечение весов ─────────────────────────────────────

weights = model.get_weights()
# [W1(6,4), b1(4), W2(4,2), b2(2), W3(2,4), b3(4), W4(4,6), b4(6)]
names = ["E1", "E2", "D1", "D2"]

min_vals = scaler.data_min_.tolist()
max_vals = scaler.data_max_.tolist()

# ─── 8. Генерация C++ заголовка ──────────────────────────────

FEATURE_NAMES = ["temperature", "humidity", "soil", "water", "light", "steam"]

def fmt_array(arr, per_line=8):
    """Форматирует numpy массив как C float инициализатор."""
    flat = arr.flatten()
    parts = [f"{v:.8e}f" for v in flat]
    lines = []
    for i in range(0, len(parts), per_line):
        chunk = parts[i:i + per_line]
        lines.append("    " + ", ".join(chunk))
    return "{\n" + ",\n".join(lines) + "\n}"

print(f"\nГенерация: {OUTPUT_PATH}")
with open(OUTPUT_PATH, "w") as f:
    f.write("// Auto-generated by train_autoencoder.py\n")
    f.write("// Do not edit manually.\n")
    f.write("#ifndef MODEL_AUTOENCODER_H\n")
    f.write("#define MODEL_AUTOENCODER_H\n\n")

    f.write("// ─── Encoder: 6 -> 4 -> 2 ────────────────────────\n")
    f.write(f"const float WEIGHT_E1[] = {fmt_array(weights[0])};\n")
    f.write(f"const float BIAS_E1[]   = {fmt_array(weights[1])};\n")
    f.write(f"const float WEIGHT_E2[] = {fmt_array(weights[2])};\n")
    f.write(f"const float BIAS_E2[]   = {fmt_array(weights[3])};\n\n")

    f.write("// ─── Decoder: 2 -> 4 -> 6 ────────────────────────\n")
    f.write(f"const float WEIGHT_D1[] = {fmt_array(weights[4])};\n")
    f.write(f"const float BIAS_D1[]   = {fmt_array(weights[5])};\n")
    f.write(f"const float WEIGHT_D2[] = {fmt_array(weights[6])};\n")
    f.write(f"const float BIAS_D2[]   = {fmt_array(weights[7])};\n\n")

    f.write("// ─── Normalisation ───────────────────────────────\n")
    f.write(f"const float NORM_MIN[] = {{{', '.join(f'{v:.1f}f' for v in min_vals)}}};\n")
    f.write(f"const float NORM_MAX[] = {{{', '.join(f'{v:.1f}f' for v in max_vals)}}};\n\n")

    f.write("// ─── Порог аномалии ─────────────────────────────\n")
    f.write(f"const float ANOMALY_THRESHOLD = {threshold:.8e}f;\n\n")

    f.write("// ─── Размерности слоёв ───────────────────────────\n")
    f.write(f"const int ENC1_ROWS = {weights[0].shape[0]}, ENC1_COLS = {weights[0].shape[1]};\n")
    f.write(f"const int ENC2_ROWS = {weights[2].shape[0]}, ENC2_COLS = {weights[2].shape[1]};\n")
    f.write(f"const int DEC1_ROWS = {weights[4].shape[0]}, DEC1_COLS = {weights[4].shape[1]};\n")
    f.write(f"const int DEC2_ROWS = {weights[6].shape[0]}, DEC2_COLS = {weights[6].shape[1]};\n\n")

    f.write("#endif\n")

print("Готово!")
print(f"Размер файла: {os.path.getsize(OUTPUT_PATH)} bytes")
